<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: hermes.proto

namespace App\Infrastructure\Grpc\Hermes;

use Spiral\RoadRunner\GRPC;

interface HermesHandlerInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hermes.HermesHandler";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HermesRequest $in
    * @return HermesResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Handle(GRPC\ContextInterface $ctx, HermesRequest $in): HermesResponse;
}
