<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hermes.proto

namespace App\Infrastructure\Grpc\GPBMetadata;

class Hermes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ï
hermes.protohermes" 
HermesRequest
payload (	" 
HermesResponse
result (	2H
HermesHandler7
Handle.hermes.HermesRequest.hermes.HermesResponseB!ÊApp\\Infrastructure\\Grpc\\Hermesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

