version: '3'

server:
    command: "php bin/console grpc:worker"

# see https://docs.roadrunner.dev/docs/plugins/grpc
grpc:
    listen: "tcp://0.0.0.0:9000"
    proto:
        - "proto/hermes.proto"
    pool:
        debug: true
#        command: "php bin/console grpc:worker"
        num_workers: 2
        max_jobs: 2
        allocate_timeout: 60s
        reset_timeout: 60s
        destroy_timeout: 60s
